import React, { useState } from 'react';
import { STS_ANNOUNCEMENTS_URL, STS_OTHER_FAMILIES, STS_SYLLABI } from '../data/stsSyllabi';

export const STSSyllabusExplorer: React.FC = () => {
  const [family, setFamily] = useState('All');
  const [selectedId, setSelectedId] = useState(STS_SYLLABI[0].id);
  const filtered = STS_SYLLABI.filter(s => family === 'All' || s.family === family);
  const selected = filtered.find(s => s.id === selectedId) ?? filtered[0];
  return <div className="rounded-3xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900 p-6 sm:p-8 space-y-6 text-slate-900 dark:text-white">
    <div><h3 className="text-xl font-bold">STS / SIBA test specifications</h3><p className="text-sm text-slate-500 mt-2">Choose a published project and post. STS does not use one universal syllabus for every test; the advertisement and its latest specifications take precedence.</p></div>
    <label className="block text-sm font-semibold">Test family<select value={family} onChange={e => {setFamily(e.target.value); setSelectedId('');}} className="block w-full sm:w-80 mt-2 p-3 rounded-xl border border-slate-300 dark:border-slate-700 bg-white dark:bg-slate-800">{['All', ...new Set(STS_SYLLABI.map(s => s.family))].map(f => <option key={f}>{f}</option>)}</select></label>
    <div className="grid md:grid-cols-[250px_1fr] gap-5"><nav aria-label="STS test specifications" className="flex md:flex-col gap-2 overflow-x-auto">{filtered.map(s => <button key={s.id} aria-current={s.id === selected.id ? 'page' : undefined} onClick={() => setSelectedId(s.id)} className={`text-left min-w-48 p-3 rounded-xl border text-sm ${s.id === selected.id ? 'border-emerald-600 bg-emerald-50 text-emerald-950 dark:bg-emerald-950 dark:text-white' : 'border-slate-200 dark:border-slate-700'}`}><span className="font-bold block">{s.name}</span><span className="text-xs block mt-1">{s.paperLevel} · {s.published.slice(0, 4)}</span></button>)}</nav>
    <article><p className="text-xs font-bold uppercase tracking-wide text-emerald-600">{selected.family} · {selected.paperLevel} level</p><h4 className="text-xl font-bold mt-2">{selected.name}</h4><p className="text-sm mt-2 text-slate-500">Published {selected.published} · 100 MCQs in this specification</p><div className="space-y-3 mt-5">{selected.sections.map(section => <section key={section.name} className="p-4 rounded-xl bg-slate-50 dark:bg-slate-800"><div className="flex justify-between gap-3 font-bold"><h5>{section.name}</h5><span>{section.percent}%</span></div><progress className="w-full accent-emerald-600 mt-2" max={100} value={section.percent} aria-label={`${section.name} percentage`}/><ul className="list-disc pl-5 mt-2 text-sm text-slate-600 dark:text-slate-300 space-y-1">{section.topics.map(topic => <li key={topic}>{topic}</li>)}</ul></section>)}</div><a href={selected.sourceUrl} target="_blank" rel="noreferrer" className="inline-block mt-5 rounded-xl bg-emerald-700 text-white px-4 py-2 font-semibold">View STS source PDF ↗</a></article></div>
    <section className="border-t border-slate-200 dark:border-slate-700 pt-5"><h4 className="font-bold">More STS test families</h4><p className="text-sm text-slate-500 mt-2">Post-level subject weights change. Open the relevant current notice before preparing.</p><ul className="list-disc pl-5 text-sm mt-3 space-y-2">{STS_OTHER_FAMILIES.map(f => <li key={f}>{f}</li>)}</ul><a href={STS_ANNOUNCEMENTS_URL} target="_blank" rel="noreferrer" className="inline-block mt-4 text-emerald-700 dark:text-emerald-400 underline font-semibold">Browse STS project announcements ↗</a></section>
  </div>;
};
