import React, { useState } from 'react';
import { BookOpen, Palette, Gamepad2, Star, Sparkles, ArrowRight, Printer, X, Waves, Pause, Play } from 'lucide-react';
import { useApp } from '../context/AppContext';
import { KIDS_WORKSHEETS } from '../data/kidsWorksheets';
import { KidsWorksheetPage } from './KidsWorksheetPage';
import { KidsGames } from './KidsGames';

const subjects=[{name:'Mathematics',emoji:'🧮',slug:'mathematics'},{name:'English',emoji:'🔤',slug:'english'},{name:'Urdu',emoji:'✍️',slug:'urdu'},{name:'Sindhi',emoji:'📜',slug:'sindhi'},{name:'Science',emoji:'🌱',slug:'everyday-science'},{name:'Islamiat',emoji:'🌙',slug:'islamic-studies'},{name:'Computer',emoji:'💻',slug:'computer'}];
const categories=['All',...new Set(KIDS_WORKSHEETS.map(item=>item.category))];

export const KidsPlayground: React.FC = () => {
  const {userProfile,setTab,setSelectedCategorySlug}=useApp();
  const [section,setSection]=useState<'learn'|'arts'|'games'>('learn');
  const [category,setCategory]=useState('All');
  const [query,setQuery]=useState('');
  const [worksheetId,setWorksheetId]=useState<string|null>(null);
  const [motion,setMotion]=useState(true);
  const worksheet=KIDS_WORKSHEETS.find(w=>w.id===worksheetId);
  const filtered=KIDS_WORKSHEETS.filter(w=>(category==='All'||w.category===category)&&`${w.title} ${w.prompt} ${w.age}`.toLowerCase().includes(query.toLowerCase()));
  const firstName=userProfile.name && userProfile.name!=='Aspirant'?userProfile.name.split(' ')[0]:'Explorer';
  const go=(tab:'mcqs'|'study-notes',slug?:string)=>{if(slug)setSelectedCategorySlug(slug);setTab(tab);window.scrollTo({top:0,behavior:'smooth'});};
  return <div className={`kids-ocean ${motion?'':'kids-ocean-paused'} relative isolate overflow-hidden rounded-[32px] border-2 border-sky-200 bg-sky-50 text-slate-900 p-4 sm:p-8`}>
    <div className="kids-water kids-water-back" aria-hidden="true"/><div className="kids-water kids-water-front" aria-hidden="true"/>
    <div className="kids-bubbles" aria-hidden="true"><i/><i/><i/><i/><i/><i/></div>
    <div className="relative z-10 space-y-7">
      <header className="rounded-3xl bg-white/90 border border-sky-200 px-5 py-6 sm:p-8 shadow-[0_14px_40px_-22px_#0369a1]">
        <div className="flex flex-wrap justify-between gap-3"><span className="inline-flex gap-2 items-center rounded-full bg-sky-100 text-sky-900 px-3 py-1.5 text-xs font-bold"><Waves size={16}/> MEQSA KIDS · CLASS 1–5</span><button className="text-xs font-bold px-3 py-2 rounded-full border border-sky-200 hover:bg-sky-100 inline-flex items-center gap-1.5" aria-pressed={!motion} onClick={()=>setMotion(v=>!v)}>{motion?<Pause size={15}/>:<Play size={15}/>} {motion?'Pause water':'Move water'}</button></div>
        <div className="flex flex-col sm:flex-row sm:items-end justify-between gap-5 mt-5"><div><h2 className="text-3xl sm:text-4xl font-black tracking-tight">👋 Hello {firstName}!</h2><p className="text-slate-600 mt-2 max-w-2xl">Welcome to your ocean of ideas. Read, make something colorful, and play to learn!</p><div className="flex flex-wrap gap-2 mt-4 text-sm font-bold"><span className="bg-amber-100 text-amber-900 rounded-full px-3 py-1.5">⭐ {userProfile.points} learning points</span><span className="bg-emerald-100 text-emerald-900 rounded-full px-3 py-1.5">🔥 {userProfile.streakDays} day streak</span></div></div><button onClick={()=>go('study-notes')} className="rounded-2xl bg-amber-400 hover:bg-amber-500 text-slate-950 px-5 py-3 font-black shadow-md inline-flex items-center gap-2">Read a kids’ lesson <ArrowRight size={18}/></button></div>
      </header>
      <nav aria-label="Kids learning areas" className="flex flex-wrap gap-2 rounded-2xl bg-white/90 border border-sky-100 p-2 w-fit shadow-sm">{([{id:'learn',label:'Today’s learning',icon:BookOpen},{id:'arts',label:'Arts & crafts',icon:Palette},{id:'games',label:'Learning games',icon:Gamepad2}] as const).map(item=>{const Icon=item.icon;return <button key={item.id} aria-current={section===item.id?'page':undefined} onClick={()=>{setSection(item.id);setWorksheetId(null);}} className={`inline-flex items-center gap-2 px-4 py-3 rounded-xl font-extrabold text-sm ${section===item.id?'bg-sky-700 text-white':'text-sky-900 hover:bg-sky-100'}`}><Icon size={18}/>{item.label}</button>})}</nav>
      {section==='learn' && <div className="space-y-7"><div><h3 className="text-xl font-black mb-4">Today’s learning</h3><div className="grid md:grid-cols-3 gap-4">{[{emoji:'🧮',title:'Mathematics',detail:'Try a number adventure',action:'Play Bubble Math',target:'games'},{emoji:'📖',title:'Read a little',detail:'Explore a simple lesson',action:'Read lesson',target:'notes'},{emoji:'🎨',title:'Create something',detail:'Pick a printable worksheet',action:'Explore worksheets',target:'arts'}].map(card=><button key={card.title} onClick={()=>card.target==='notes'?go('study-notes'):setSection(card.target as 'games'|'arts')} className="rounded-2xl border border-sky-200 bg-white p-5 text-left shadow-sm hover:-translate-y-1 hover:shadow-md transition-transform"><span className="text-3xl">{card.emoji}</span><span className="block text-lg font-black mt-3">{card.title}</span><span className="block text-sm text-slate-600 mt-1">{card.detail}</span><span className="inline-flex gap-1 items-center mt-4 font-bold text-sky-800 text-sm">{card.action} <ArrowRight size={16}/></span></button>)}</div></div><div><h3 className="text-sm uppercase tracking-widest text-sky-800 font-black mb-3">All Class 1–5 subjects</h3><div className="grid grid-cols-2 sm:grid-cols-4 lg:grid-cols-7 gap-3">{subjects.map(sub=><button key={sub.name} onClick={()=>go('mcqs',sub.slug)} className="rounded-2xl bg-white border border-sky-200 p-4 text-center hover:bg-sky-100 hover:-translate-y-1 transition-transform"><span className="block text-3xl">{sub.emoji}</span><span className="block text-xs sm:text-sm font-bold mt-2">{sub.name}</span></button>)}</div></div><div className="grid sm:grid-cols-2 gap-4"><button onClick={()=>setSection('arts')} className="rounded-3xl bg-pink-100 border border-pink-200 p-6 text-left"><Palette size={27} className="text-pink-700"/><span className="block text-xl font-black mt-2">Printable creative studio</span><span className="text-sm">{KIDS_WORKSHEETS.length} things to trace, color, cut and make →</span></button><button onClick={()=>setSection('games')} className="rounded-3xl bg-amber-100 border border-amber-200 p-6 text-left"><Sparkles size={27} className="text-amber-700"/><span className="block text-xl font-black mt-2">Play to learn</span><span className="text-sm">Math, memory and spelling games →</span></button></div></div>}
      {section==='arts' && <div className="space-y-5"><div className="flex flex-wrap justify-between gap-3"><div><span className="text-sm font-black text-pink-700 uppercase tracking-widest">CREATE SOMETHING GREAT</span><h3 className="text-3xl font-black">Arts & craft worksheets</h3><p className="text-slate-600 mt-1">{KIDS_WORKSHEETS.length} ready-to-print activities. Choose one to see the full page.</p></div><span className="text-4xl" aria-hidden="true">🎨</span></div>{worksheet?<div className="space-y-4"><div className="flex flex-wrap gap-3 items-center"><button className="rounded-xl bg-sky-700 text-white px-5 py-3 font-bold inline-flex items-center gap-2 hover:bg-sky-800" onClick={()=>window.print()}><Printer size={19}/>Print worksheet</button><button className="rounded-xl border border-sky-300 px-4 py-3 font-bold hover:bg-sky-100 inline-flex gap-1 items-center" onClick={()=>setWorksheetId(null)}><X size={18}/>Back to all activities</button></div><KidsWorksheetPage worksheet={worksheet}/></div>:<><div className="flex flex-wrap gap-3"><label className="font-bold text-sm">Find an activity<input className="block mt-1 rounded-xl border border-sky-300 bg-white p-3 w-60 max-w-full" value={query} placeholder="Search worksheets" onChange={e=>setQuery(e.target.value)}/></label><label className="font-bold text-sm">Activity type<select className="block mt-1 rounded-xl border border-sky-300 bg-white p-3" value={category} onChange={e=>setCategory(e.target.value)}>{categories.map(c=><option key={c}>{c}</option>)}</select></label></div><div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4">{filtered.map(w=><button key={w.id} onClick={()=>setWorksheetId(w.id)} className="group rounded-2xl border border-sky-200 bg-white p-5 text-left hover:shadow-md hover:-translate-y-1 transition-transform"><span className="text-3xl">{w.kind==='craft'?'✂️':w.kind==='color'?'🖍️':w.kind==='dots'?'🔵':w.kind==='count'?'🌻':'✏️'}</span><span className="block text-xs uppercase tracking-wide text-sky-700 font-bold mt-2">{w.category} · {w.age}</span><span className="block text-lg font-black mt-1">{w.title}</span><span className="block text-sm text-slate-600 mt-1">{w.prompt}</span><span className="inline-flex items-center text-sm font-bold text-sky-800 mt-4 gap-1">Preview & print <ArrowRight size={15}/></span></button>)}</div>{!filtered.length&&<p role="status">No worksheets found. Try a different search.</p>}</>}</div>}
      {section==='games'&&<KidsGames/>}
    </div>
  </div>;
};
